# Generated by Django 5.2.17 on 2026-09-28 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('application_name', models.CharField(default='Gramaswaraj Media Facilitator Management System', max_length=160)),
                ('short_name', models.CharField(default='Gramaswaraj', max_length=30)),
                ('name', models.CharField(default='Kerala Grama Panchayat Association', max_length=180)),
                ('name_ml', models.CharField(default='ഗ്രാമസ്വരാജ് മീഡിയ ഫെസിലിറ്റേറ്റർ മാനേജ്മെന്റ് സിസ്റ്റം', max_length=200)),
                ('network_name', models.CharField(default='Digital Media & Broadcasting Network', max_length=180)),
                ('address', models.TextField(blank=True, max_length=1500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('signatory_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_organization_setting')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('facilitator_id_prefix', models.CharField(default='GS-MF', max_length=12, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9-]*$')])),
                ('default_validity_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('one_primary_per_panchayat', models.BooleanField(default=True)),
                ('public_directory_enabled', models.BooleanField(default=False)),
                ('allow_public_mobile', models.BooleanField(default=False)),
                ('allow_public_email', models.BooleanField(default=False)),
                ('allow_public_social_profiles', models.BooleanField(default=False)),
                ('max_upload_mb', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('consent_version', models.CharField(default='1.0', max_length=30)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_system_setting')],
            },
        ),
    ]
