# Generated by Django 5.2.17 on 2026-09-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_requestbudget'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjurisdiction',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='locations.block'),
        ),
        migrations.AddField(
            model_name='userjurisdiction',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='locations.district'),
        ),
    ]
