# Generated by Django 5.2.17 on 2026-09-28 16:52

import apps.facilitators.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('registrations', '0004_application_decided_at_application_decided_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorSequence',
            fields=[
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='locations.district')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facilitator_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REPLACED', 'Replaced'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('verification_token', models.CharField(default=apps.facilitators.models.verification_token, editable=False, max_length=64, unique=True)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facilitator', to='registrations.application')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityCardMetadata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('valid_until', models.DateField()),
                ('facilitator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initial_card', to='facilitators.facilitator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitatorAppointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('ASSISTANT', 'Assistant'), ('ADDITIONAL', 'Additional')], default='PRIMARY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REPLACED', 'Replaced'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilitators.facilitator')),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='locations.gramapanchayat')),
            ],
            options={
                'indexes': [models.Index(fields=['panchayat', 'role', 'status'], name='facilitator_panchay_ce3b41_idx')],
            },
        ),
    ]
