# Generated by Django 5.2.17 on 2026-09-29 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='current_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='facilitators.facilitatorappointment'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facilitatorappointment',
            name='end_reason',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='facilitatorappointment',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacilitatorStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=2000)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='facilitators.facilitatorappointment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='facilitators.facilitator')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('view',),
            },
        ),
    ]
