# Generated by Django 5.2.17 on 2026-09-29 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0003_backfill_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorappointment',
            name='appointment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facilitatorappointment',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facilitatorappointment',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
