import {randomUUID} from 'node:crypto';
import {can,loadUser,capabilities} from './policies.js';
import {FormError,catalog} from './registration-fields.js';
import {hashPassword,verifyPassword} from './security.js';
import {policyLock} from './registration-services.js';
import {settings,organizationDefaults} from './settings.js';
export const roles=Object.keys(capabilities);
async function actor(tx,id,cap){const user=await loadUser(tx,id);if(!can(user,cap))throw new FormError('Administration access denied.',403);return user;}
function reason(input){const value=input.reason;if(typeof value!=='string'||!value.trim()||value.trim().length>2000)throw new FormError('Provide a reason within 2,000 characters.');return value.trim();}
export async function auditChange(tx,userId,action,entity,note,changes){const id=randomUUID();await tx.run('INSERT INTO gmf_audit(id,user_id,action,created_at) VALUES (?,?,?,?)',[id,userId,action,Date.now()]);await tx.run('INSERT INTO gmf_audit_details(id,entity,reason,changes) VALUES (?,?,?,?)',[id,entity,note,JSON.stringify(changes)]);}
async function invalidateSessions(tx,userId){for(const row of await tx.all('SELECT id,payload FROM gmf_sessions')){let data;try{data=JSON.parse(row.payload);}catch{continue;}if(data.userId===userId)await tx.run('DELETE FROM gmf_sessions WHERE id=?',[row.id]);}}
export async function accountAction(db,actorId,input){
 let password=null;try{if(['create','password'].includes(input.action))password=await hashPassword(input.password);}catch{throw new FormError('Use a password of 12–256 characters.');}
 return db.transaction(async tx=>{await policyLock(tx);const manager=await actor(tx,actorId,'accounts.manage'),note=reason(input);
 if(input.action==='create'){const username=typeof input.username==='string'?input.username.trim().toLowerCase():'',email=typeof input.email==='string'?input.email.trim().toLowerCase():'';if(!/^[a-z0-9_.-]{3,150}$/.test(username)||!/^\S+@\S+\.\S+$/.test(email)||email.length>254)throw new FormError('Provide a valid username and email.');if((await tx.all('SELECT id FROM gmf_users WHERE username=? OR email=?',[username,email])).length)throw new FormError('This username or email is already in use.');const id=randomUUID();await tx.run('INSERT INTO gmf_users(id,username,email,password_hash) VALUES (?,?,?,?)',[id,username,email,password]);await tx.run('INSERT INTO gmf_account_meta(id,must_change) VALUES (?,1)',[id]);await auditChange(tx,actorId,'account.created',id,note,{username,email});return id;}
 const user=(await tx.all('SELECT id,username,active,superuser FROM gmf_users WHERE id=?',[input.user_id||'']))[0];if(!user)throw new FormError('Account unavailable.',404);await tx.run('INSERT OR IGNORE INTO gmf_account_meta(id) VALUES (?)',[user.id]);const meta=(await tx.all('SELECT revision FROM gmf_account_meta WHERE id=?',[user.id]))[0];if(meta.revision!==Number(input.revision))throw new FormError('This account changed. Reload before continuing.',409);
 const changes={};
 if(input.action==='active'){const active=input.active==='on'?1:0;if(user.id===manager.id&&!active)throw new FormError('Use another administrator to deactivate your own account.');await tx.run('UPDATE gmf_users SET active=? WHERE id=?',[active,user.id]);changes.active=active;if(!active)await invalidateSessions(tx,user.id);}
 else if(input.action==='password'){if(user.id===manager.id)throw new FormError('Use your Change password page for your own account.');await tx.run('UPDATE gmf_users SET password_hash=? WHERE id=?',[password,user.id]);await tx.run('UPDATE gmf_account_meta SET must_change=1 WHERE id=?',[user.id]);await invalidateSessions(tx,user.id);changes.password_reset=true;}
 else if(input.action==='assign'){const role=input.role,scope=input.scope,district=input.district||null,block=input.block||null;if([district,block].some(v=>v!==null&&(typeof v!=='string'||v.length>30)))throw new FormError('Choose valid location codes.');if(!roles.includes(role)||!['STATE','DISTRICT','BLOCK'].includes(scope))throw new FormError('Choose a valid role and scope.');if(['SUPER_ADMIN','STATE_ADMIN'].includes(role)&&scope!=='STATE'||role==='DISTRICT_ADMIN'&&scope!=='DISTRICT'||role==='BLOCK_COORDINATOR'&&scope!=='BLOCK')throw new FormError('This role requires its matching state, district or block scope.');if(scope==='STATE'&&(district||block)||scope==='DISTRICT'&&(!district||block)||scope==='BLOCK'&&(!district||!block))throw new FormError('Check the scope location fields.');if(scope!=='STATE'){const places=await tx.all('SELECT d.code FROM gmf_districts d JOIN gmf_states s ON s.code=d.state_code WHERE d.code=? AND d.active=1 AND s.active=1',[district]);if(!places.length)throw new FormError('Select an active district.');if(scope==='BLOCK'&&!(await tx.all('SELECT code FROM gmf_blocks WHERE code=? AND district_code=? AND active=1',[block,district])).length)throw new FormError('Select an active block within that district.');}await tx.run('INSERT INTO gmf_scopes(id,user_id,role,scope,district_code,block_code) VALUES (?,?,?,?,?,?)',[randomUUID(),user.id,role,scope,district,block]);Object.assign(changes,{role,scope,district,block});}
 else if(input.action==='remove'){const assignment=(await tx.all('SELECT id FROM gmf_scopes WHERE id=? AND user_id=? AND active=1',[input.assignment_id||'',user.id]))[0];if(!assignment)throw new FormError('Role assignment unavailable.');await tx.run('UPDATE gmf_scopes SET active=0 WHERE id=?',[assignment.id]);changes.assignment_removed=assignment.id;}
 else throw new FormError('Unknown account action.');
 const activeUsers=await tx.all('SELECT id FROM gmf_users WHERE active=1');let managers=0;for(const row of activeUsers){if(can(await loadUser(tx,row.id),'accounts.manage'))managers++;}if(!managers)throw new FormError('At least one active administrator with account-management access is required.');
 await tx.run('UPDATE gmf_account_meta SET revision=revision+1 WHERE id=?',[user.id]);await auditChange(tx,actorId,'account.'+input.action,user.id,note,changes);return user.id;
 });}
export async function changePassword(db,id,input){let encoded;try{encoded=await hashPassword(input.password);}catch{throw new FormError('Use a password of 12–256 characters.');}return db.transaction(async tx=>{await policyLock(tx);const user=(await tx.all('SELECT password_hash FROM gmf_users WHERE id=? AND active=1',[id]))[0];if(!user||!await verifyPassword(input.current_password,user.password_hash))throw new FormError('Current password is incorrect.');if(await verifyPassword(input.password,user.password_hash))throw new FormError('Choose a new password.');await tx.run('UPDATE gmf_users SET password_hash=? WHERE id=?',[encoded,id]);await tx.run('INSERT OR IGNORE INTO gmf_account_meta(id) VALUES (?)',[id]);await tx.run('UPDATE gmf_account_meta SET must_change=0,revision=revision+1 WHERE id=?',[id]);await invalidateSessions(tx,id);await auditChange(tx,id,'account.password_changed',id,'Account owner changed their password.',{});});}
export async function updateSettings(db,actorId,kind,input){return db.transaction(async tx=>{await policyLock(tx);await actor(tx,actorId,kind==='organization'?'organization.change':'system.change');const row=await settings(tx,kind),note=reason(input);if(row.revision!==Number(input.revision))throw new FormError('Settings changed. Reload before saving.',409);let data={};
 if(kind==='organization'){const lengths={application_name:160,short_name:30,name:180,network_name:180,address:1500,phone:30,email:254,website:250,signatory_name:120};for(const [key,max] of Object.entries(lengths)){if(typeof input[key]!=='string'||input[key].trim().length>max||['application_name','short_name','name','network_name'].includes(key)&&!input[key].trim())throw new FormError('Check the organization fields.');data[key]=input[key].trim();}if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))throw new FormError('Enter a valid email.');if(data.website){try{const url=new URL(data.website);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error();}catch{throw new FormError('Enter an HTTP or HTTPS website without embedded credentials.');}}}
 else if(kind==='system'){const prefix=input.prefix,days=Number(input.validity_days),version=input.consent_version;if(typeof prefix!=='string'||!/^[A-Z][A-Z0-9-]{0,11}$/.test(prefix)||!Number.isInteger(days)||days<1||days>3650||typeof version!=='string'||!/^[A-Za-z0-9._-]{1,30}$/.test(version))throw new FormError('Check ID prefix, validity days and consent version.');const docs=input.required_documents===undefined?[]:Array.isArray(input.required_documents)?input.required_documents:[input.required_documents];if(docs.some(code=>!catalog.DOCUMENTS.some(([c])=>c===code)))throw new FormError('Choose valid required document types.');data={required_documents:[...new Set(docs)]};for(const key of ['registration_open','allow_public_mobile','allow_public_email','allow_public_social'])data[key]=input[key]==='on';await tx.run('UPDATE gmf_registration_policy SET prefix=?,validity_days=?,consent_version=? WHERE id=1',[prefix,days,version]);}
 else throw new FormError('Unknown settings page.');await tx.run('UPDATE gmf_settings SET payload=?,revision=revision+1 WHERE id=?',[JSON.stringify(data),kind]);await auditChange(tx,actorId,'settings.'+kind,kind,note,{changed_fields:Object.keys(data)});
 });}
