import express from 'express';
import {can} from './policies.js';
import {FormError,catalog} from './registration-fields.js';
import {settings} from './settings.js';
import {accountAction,changePassword,updateSettings,roles} from './administration.js';
import {budget} from './security.js';
export function administrationRoutes(db,cfg){const r=express.Router();
 const requireCap=cap=>(req,res,next)=>{if(!can(res.locals.user,cap))throw new FormError('Administration access denied.',403);next();};
 const rate=async(req)=>{if(!await budget(db,cfg.secret,'administration',resUser(req),30,3600000))throw new FormError('Too many account or settings changes. Try again later.',429);};const resUser=req=>req.session.userId;
 r.get('/accounts/password/',(req,res)=>res.render('password',{error:''}));r.post('/accounts/password/',async(req,res)=>{await rate(req);try{if(req.body.password!==req.body.confirm_password)throw new FormError('New passwords must match.');await changePassword(db,req.session.userId,req.body);await new Promise((resolve,reject)=>req.session.destroy(e=>e?reject(e):resolve()));res.clearCookie('gmf.sid');res.redirect('/accounts/login/');}catch(e){if(!(e instanceof FormError))throw e;res.status(e.status).render('password',{error:e.message});}});
 r.get('/administration/',(req,res)=>{const access={accounts:can(res.locals.user,'accounts.manage'),organization:can(res.locals.user,'organization.change'),system:can(res.locals.user,'system.change'),audit:can(res.locals.user,'audit.view')};if(!Object.values(access).some(Boolean))throw new FormError('Administration access denied.',403);res.render('administration',{access});});
 r.get('/administration/accounts/',requireCap('accounts.manage'),async(req,res)=>{const users=await db.all('SELECT u.id,u.username,u.email,u.active,u.superuser,COALESCE(m.revision,1) AS revision FROM gmf_users u LEFT JOIN gmf_account_meta m ON m.id=u.id ORDER BY u.username LIMIT 1000');const scopes=await db.all('SELECT id,user_id,role,scope,district_code,block_code FROM gmf_scopes WHERE active=1');const districts=await db.all('SELECT code,name FROM gmf_districts WHERE active=1 ORDER BY name'),blocks=await db.all('SELECT code,name,district_code FROM gmf_blocks WHERE active=1 ORDER BY name');res.render('accounts',{users,scopes,roles,districts,blocks});});
 r.post('/administration/accounts/',requireCap('accounts.manage'),async(req,res)=>{await rate(req);if(['create','password'].includes(req.body.action)&&req.body.password!==req.body.confirm_password)throw new FormError('Passwords must match.');await accountAction(db,req.session.userId,req.body);res.redirect('/administration/accounts/');});
 for(const kind of ['organization','system']){const cap=kind==='organization'?'organization.change':'system.change';r.get('/administration/'+kind+'/',requireCap(cap),async(req,res)=>{const value=await settings(db,kind),policy=(await db.all('SELECT prefix,validity_days,consent_version FROM gmf_registration_policy WHERE id=1'))[0];res.render('settings',{kind,value,policy,catalog});});r.post('/administration/'+kind+'/',requireCap(cap),async(req,res)=>{await rate(req);await updateSettings(db,req.session.userId,kind,req.body);res.redirect('/administration/'+kind+'/');});}
 r.get('/administration/audit/',requireCap('audit.view'),async(req,res)=>{const raw=req.query.page||'1';if(typeof raw!=='string'||!/^\d{1,5}$/.test(raw))throw new FormError('Invalid audit page.');const page=Math.max(1,Number(raw)),offset=(page-1)*50;const rows=await db.all(`SELECT a.action,a.created_at,u.username,d.entity,d.reason,d.changes FROM gmf_audit a LEFT JOIN gmf_users u ON u.id=a.user_id LEFT JOIN gmf_audit_details d ON d.id=a.id ORDER BY a.created_at DESC,a.id DESC LIMIT 51 OFFSET ${offset}`);res.render('audit',{rows:rows.slice(0,50),page,more:rows.length>50});});
 return r;}
