import {settings} from './settings.js';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {can,loadUser} from './policies.js';
import {FormError} from './registration-fields.js';
import {facilitator,today,effectiveStatus,registrySelect} from './registry.js';
import {policyLock} from './registration-services.js';
import {renderCards,logoPath,fontPath,latinFontPath} from './card-rendering.js';
export const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const assetHash=hash(Buffer.concat([readFileSync(logoPath),readFileSync(fontPath),readFileSync(latinFontPath)]));
export async function authorization(db,f){if(f.status!=='ACTIVE')return f.status;if(f.valid_until<today())return 'EXPIRED';if(f.ended)return 'INACTIVE';const rows=await db.all(`SELECT p.code FROM gmf_panchayats p JOIN gmf_blocks b ON b.code=p.block_code JOIN gmf_districts d ON d.code=b.district_code JOIN gmf_states s ON s.code=d.state_code JOIN gmf_applications a ON a.id=? WHERE p.code=? AND a.status='APPROVED' AND p.active=1 AND b.active=1 AND d.active=1 AND s.active=1`,[f.application_id,f.panchayat_code]);return rows.length?'ACTIVE':'INACTIVE';}
export async function verificationToken(db,id){return (await db.all('SELECT token FROM gmf_verification WHERE facilitator_id=?',[id]))[0]?.token;}
export async function source(db,f,cfg){
 const app=(await db.all('SELECT payload FROM gmf_applications WHERE id=?',[f.application_id]))[0],portrait=(await db.all("SELECT body,sha256 FROM gmf_uploads WHERE owner_id=? AND slot='photo' AND mime='image/jpeg'",[f.application_id]))[0];if(!app||!portrait)throw new FormError('A validated portrait and approved application are required.');
 const token=await verificationToken(db,f.id);if(!token)throw new FormError('Create a verification link first.');
 const place=(await db.all('SELECT b.name AS block,d.name AS district FROM gmf_blocks b JOIN gmf_districts d ON d.code=b.district_code WHERE b.code=?',[f.block_code]))[0];
 const epoch=(await db.all("SELECT COUNT(*) AS n FROM gmf_registry_history WHERE facilitator_id=? AND action IN ('transfer','role','resign','reactivate','replace')",[f.id]))[0].n;
 const organization=(await settings(db,'organization')).data;
 const snapshot={brand:organization.short_name,organization:organization.name,network:organization.network_name,signatory:organization.signatory_name,name:f.full_name,name_ml:JSON.parse(app.payload)[2].name_ml||'',number:f.number,panchayat:f.panchayat_name,block:place.block,district:place.district,role:f.role,valid_until:f.valid_until,portrait_hash:portrait.sha256,epoch,assets:assetHash,template:'node-1',verification_url:cfg.origin+'/verify/'+token+'/',preview:!cfg.production};
 return {snapshot,digest:hash(JSON.stringify(snapshot)),portrait};
}
export async function cardState(db,card,f,cfg){if(card.status!=='ISSUED')return card.status;if(card.valid_until<today())return 'EXPIRED';if(await authorization(db,f)!=='ACTIVE')return 'INACTIVE';try{return (await source(db,f,cfg)).digest===card.source_hash?'CURRENT':'OUTDATED';}catch{return 'OUTDATED';}}
async function event(tx,f,user,action,reason,card=null){await tx.run('INSERT INTO gmf_card_events(id,facilitator_id,card_id,actor_id,action,reason,created_at) VALUES (?,?,?,?,?,?,?)',[randomUUID(),f.id,card,user.id,action,reason,Date.now()]);await tx.run('INSERT INTO gmf_audit(id,user_id,action,created_at) VALUES (?,?,?,?)',[randomUUID(),user.id,'card.'+action,Date.now()]);}
async function bump(tx,f){await tx.run("INSERT OR IGNORE INTO gmf_registry_meta(id,notes) VALUES (?,'')",[f.id]);await tx.run('UPDATE gmf_registry_meta SET revision=revision+1 WHERE id=?',[f.id]);}
function reason(input){if(typeof input.reason!=='string'||!input.reason.trim()||input.reason.trim().length>2000)throw new FormError('Provide a reason within 2,000 characters.');return input.reason.trim();}
export async function cardAction(db,cfg,userId,id,input){return db.transaction(async tx=>{
 await policyLock(tx);const user=await loadUser(tx,userId),rotation=input.action==='rotate',f=await facilitator(tx,id,user,rotation?'facilitators.change':'cards.issue');if(f.revision!==Number(input.revision))throw new FormError('The facilitator changed. Reload before continuing.',409);const note=reason(input);
 if(input.action==='create_link'||rotation){if(rotation&&input.confirmed!=='on')throw new FormError('Confirm that existing links and QR codes will stop working.');if(!rotation&&await verificationToken(tx,id))throw new FormError('A verification link already exists.');await tx.run('DELETE FROM gmf_verification WHERE facilitator_id=?',[id]);await tx.run('INSERT INTO gmf_verification(facilitator_id,token) VALUES (?,?)',[id,randomBytes(32).toString('hex')]);await bump(tx,f);await event(tx,f,user,rotation?'token_rotated':'link_created',note);return;}
 if(input.action==='issue'){
 if(await authorization(tx,f)!=='ACTIVE')throw new FormError('Only active approved facilitators can receive a card.');if(!await verificationToken(tx,id))await tx.run('INSERT INTO gmf_verification(facilitator_id,token) VALUES (?,?)',[id,randomBytes(32).toString('hex')]);
 const {snapshot,digest,portrait}=await source(tx,f,cfg),photo=Buffer.from(portrait.body,'base64');if(hash(photo)!==portrait.sha256)throw new FormError('Portrait integrity check failed.');
 const version=Number((await tx.all('SELECT MAX(version) AS n FROM gmf_cards WHERE facilitator_id=?',[id]))[0].n||0)+1,cardId=randomUUID(),token=randomBytes(32).toString('hex'),number=f.number+'-V'+String(version).padStart(3,'0');const cardSnapshot={...snapshot,card_number:number,issued_on:today(),version};const files=await renderCards(cardSnapshot,photo,snapshot.verification_url+'?card='+token);
 await tx.run("UPDATE gmf_cards SET status='SUPERSEDED' WHERE facilitator_id=? AND status='ISSUED'",[id]);await tx.run('INSERT INTO gmf_cards(id,facilitator_id,number,version,token,source_hash,snapshot,pdf,print_pdf,pdf_hash,print_hash,issued_on,valid_until) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[cardId,id,number,version,token,digest,JSON.stringify(cardSnapshot),files.pdf.toString('base64'),files.print_pdf.toString('base64'),hash(files.pdf),hash(files.print_pdf),today(),f.valid_until]);await bump(tx,f);await event(tx,f,user,'issued',note,cardId);return cardId;
 }
 const card=(await tx.all('SELECT * FROM gmf_cards WHERE id=? AND facilitator_id=?',[input.card_id||'',id]))[0];if(!card)throw new FormError('Card unavailable.',404);
 if(input.action==='revoke'){if(!can(user,'facilitators.change',f))throw new FormError('Access denied.',403);if(card.status!=='ISSUED')throw new FormError('Only an issued card can be revoked.');await tx.run("UPDATE gmf_cards SET status='REVOKED' WHERE id=?",[card.id]);await bump(tx,f);await event(tx,f,user,'revoked',note,card.id);return;}
 if(input.action==='download'){if(await cardState(tx,card,f,cfg)!=='CURRENT')throw new FormError('This card is no longer current. Generate a new version.');if(!['pdf','print_pdf'].includes(input.format))throw new FormError('Choose a valid PDF format.');const bytes=Buffer.from(card[input.format],'base64');if(hash(bytes)!==card[input.format==='pdf'?'pdf_hash':'print_hash'])throw new FormError('Stored card integrity check failed.');await event(tx,f,user,'downloaded',note,card.id);return {bytes,number:card.number};}
 throw new FormError('Unknown card action.');
 });}
export async function lookup(db,token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))return null;return (await db.all(registrySelect+" JOIN gmf_verification v ON v.facilitator_id=f.id JOIN gmf_applications a ON a.id=f.application_id WHERE v.token=? AND a.status='APPROVED'",[token]))[0]||null;}
export async function publicProfile(db,f,cfg,token,cardToken){
 const state=await authorization(db,f),place=(await db.all('SELECT b.name AS block,d.name AS district FROM gmf_blocks b JOIN gmf_districts d ON d.code=b.district_code WHERE b.code=?',[f.block_code]))[0];
 const profile={name:f.full_name,facilitator_id:f.number,role:f.role,panchayat:f.panchayat_name,block:place.block,district:place.district,status:state,is_authorized:state==='ACTIVE',valid_until:f.valid_until,portrait_url:'/verify/'+token+'/portrait/',organization:(await settings(db,'organization')).data.name};
 if(cardToken!==undefined){if(typeof cardToken!=='string'||!/^[a-f0-9]{64}$/.test(cardToken))return null;const card=(await db.all('SELECT id,number,version,status,valid_until,issued_on,source_hash FROM gmf_cards WHERE facilitator_id=? AND token=?',[f.id,cardToken]))[0];if(!card)return null;const status=await cardState(db,card,f,cfg);profile.card={number:card.number,version:card.version,status,issued_on:card.issued_on,valid_until:card.valid_until};if(status!=='CURRENT'){profile.identity_status=profile.status;profile.status=status==='REVOKED'?'REVOKED':status==='EXPIRED'?'EXPIRED':'INACTIVE';profile.is_authorized=false;}}
 if(profile.is_authorized){const policy=(await settings(db,'system')).data,app=JSON.parse((await db.all('SELECT payload FROM gmf_applications WHERE id=?',[f.application_id]))[0].payload);if(policy.allow_public_mobile&&app.consent?.public_mobile&&app[2]?.mobile)profile.mobile=app[2].mobile;if(policy.allow_public_email&&app.consent?.public_email&&app[2]?.email)profile.email=app[2].email;if(policy.allow_public_social&&app.consent?.public_social){const social={};for(const key of ['facebook','instagram','youtube','twitter','linkedin','other_profile']){const value=app[4]?.[key];if(typeof value!=='string'||!value||value.length>250)continue;try{const url=new URL(value);if(['http:','https:'].includes(url.protocol)&&!url.username&&!url.password)social[key]=value;}catch{}}if(Object.keys(social).length)profile.social_profiles=social;}}
 return profile;
}
