import express from 'express';
import {randomUUID} from 'node:crypto';
import {reportKinds,statuses,reportData,placesFor,snapshot,summarize,hasCapability} from './reports.js';
import {loadUser} from './policies.js';
import {policyLock} from './registration-services.js';
import {FormError} from './registration-fields.js';
import {budget} from './security.js';
import {exportBytes} from './report-exporting.js';
import {today} from './registry.js';
export async function generateExport(db,cfg,userId,filters,input){
 if(typeof input.reason!=='string'||!input.reason.trim()||input.reason.trim().length>500)throw new FormError('Provide an export reason within 500 characters.');if(!['csv','xlsx','pdf'].includes(input.format))throw new FormError('Choose Excel, CSV or PDF.');
 return db.transaction(async tx=>{await policyLock(tx);const user=await loadUser(tx,userId),report=await reportData(tx,user,filters,true);const description='As of '+new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST · '+report.rows.length+' rows · '+Object.entries(report.filters).map(([k,v])=>k+': '+v).join('; ')+' · Permitted jurisdiction only.';const result=await exportBytes(input.format,report,description);const id=randomUUID(),at=Date.now();await tx.run('INSERT INTO gmf_report_exports(id,actor_id,report,format,row_count,filters,reason,created_at) VALUES (?,?,?,?,?,?,?,?)',[id,userId,report.filters.report,input.format,report.rows.length,JSON.stringify(report.filters),input.reason.trim(),at]);await tx.run('INSERT INTO gmf_audit(id,user_id,action,created_at) VALUES (?,?,?,?)',[randomUUID(),userId,'reports.exported',at]);return {...result,filename:`gramaswaraj-${report.filters.report}-${today()}.${input.format}`};});
}
export function reportRoutes(db,cfg){const r=express.Router();
 r.get('/',async(req,res)=>{const user=res.locals.user;if(!hasCapability(user,'dashboard.view'))throw new FormError('Access denied.',403);const places=await placesFor(db,user,'dashboard.view'),data=await snapshot(db,user,places),summary=summarize(data,user),districts=[...new Set(places.map(p=>p.district_code))].map(code=>{const group=places.filter(p=>p.district_code===code),ids=new Set(group.map(p=>p.code));return {name:group[0].district_name,...summarize({places:group,fs:data.fs.filter(f=>ids.has(f.panchayat_code)),apps:data.apps.filter(a=>ids.has(a.panchayat_code))},user)};});res.render('dashboard',{summary,districts});});
 async function render(req,res,error=''){const user=res.locals.user;let report;try{report=await reportData(db,user,req.query);}catch(e){if(!(e instanceof FormError)||e.status===403)throw e;error=e.message;res.status(400);report={headers:[],rows:[],filters:{report:'coverage',...Object.fromEntries(Object.entries(req.query).filter(([,v])=>typeof v==='string'&&v.length<41))},options:await placesFor(db,user,'dashboard.view'),title:'Reports'};}const rawPage=req.query.page??'1';if(typeof rawPage!=='string'||!/^\d{1,6}$/.test(rawPage))throw new FormError('Choose a valid page.');const pages=Math.max(1,Math.ceil(report.rows.length/50)),page=Math.min(pages,Math.max(1,Number(rawPage))),query=new URLSearchParams(report.filters).toString();res.render('reports',{reportKinds,statuses,report,rows:report.rows.slice((page-1)*50,page*50),total:report.rows.length,page,pages,query,error,canExport:hasCapability(user,'reports.export')});}
 r.get('/reports/',async(req,res)=>render(req,res));
 r.post('/reports/',async(req,res)=>{if(!hasCapability(res.locals.user,'reports.export'))throw new FormError('Export access denied.',403);if(!await budget(db,cfg.secret,'report-export',res.locals.user.id,30,3600000))throw new FormError('Too many exports. Please try again later.',429);try{const output=await generateExport(db,cfg,res.locals.user.id,req.query,req.body);res.set('Content-Disposition',`attachment; filename="${output.filename}"`);res.type(output.mime).send(output.bytes);}catch(e){if(!(e instanceof FormError)||e.status===403)throw e;res.status(400);await render(req,res,e.message);}});return r;
}
