import {can,scopesFor} from './policies.js';
import {FormError} from './registration-fields.js';
import {registrySelect,effectiveStatus,today} from './registry.js';
export const reportKinds={coverage:'Coverage',progress:'Registration progress',skills:'Facilitator skills',equipment:'Equipment availability',history:'Appointment change history',vacancies:'Vacant panchayats',facilitators:'Facilitators',applications:'Applications',expiring:'Expiring within 30 days'};
export const statuses=['ACTIVE','INACTIVE','SUSPENDED','EXPIRED','REPLACED','REVOKED','PENDING','SUBMITTED','UNDER_REVIEW','CORRECTION_REQUIRED','APPROVED','REJECTED','WITHDRAWN'];
const pending=new Set(['SUBMITTED','UNDER_REVIEW','CORRECTION_REQUIRED']);
export const hasCapability=(user,cap)=>!!user?.active&&(!!user.superuser||scopesFor(user,cap).length>0);
export const dateOf=ms=>new Date(Number(ms)).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export async function placesFor(db,user,capability){return (await db.all(`SELECT p.code,p.name,b.code AS block_code,b.name AS block_name,d.code AS district_code,d.name AS district_name FROM gmf_panchayats p JOIN gmf_blocks b ON b.code=p.block_code JOIN gmf_districts d ON d.code=b.district_code JOIN gmf_states s ON s.code=d.state_code WHERE p.active=1 AND b.active=1 AND d.active=1 AND s.active=1 ORDER BY d.name,b.name,p.name`)).filter(p=>can(user,capability,p));}
export function validateFilters(input,places){const f={report:'coverage',date_field:'registration'};for(const key of ['report','district','block','panchayat','status','role','date_field','start','end'])if(input[key]!==undefined&&input[key]!==''){if(typeof input[key]!=='string'||input[key].length>40)throw new FormError('Invalid report filter.');f[key]=input[key];}
 if(!Object.hasOwn(reportKinds,f.report)||!['registration','approval','expiry'].includes(f.date_field)||f.status&&!statuses.includes(f.status)||f.role&&!['PRIMARY','ASSISTANT','ADDITIONAL'].includes(f.role))throw new FormError('Choose valid report filters.');
 for(const key of ['start','end'])if(f[key]){const d=new Date(f[key]);if(!/^\d{4}-\d{2}-\d{2}$/.test(f[key])||Number.isNaN(+d)||d.toISOString().slice(0,10)!==f[key])throw new FormError('Enter valid filter dates.');}
 if(f.start&&f.end&&f.start>f.end)throw new FormError('Start date must not follow end date.');
 const selected=places.filter(p=>(!f.district||p.district_code===f.district)&&(!f.block||p.block_code===f.block)&&(!f.panchayat||p.code===f.panchayat));if((f.district||f.block||f.panchayat)&&!selected.length)throw new FormError('Choose locations within your permitted jurisdiction and the same hierarchy.',403);
 if(['coverage','vacancies'].includes(f.report)&&[f.status,f.role,f.start,f.end].some(Boolean))throw new FormError('Coverage and vacancies are current snapshots. Use location filters only.');
 const appReport=['applications','progress'].includes(f.report);if(appReport&&(f.role||f.date_field!=='registration'))throw new FormError('Application reports support registration dates and application statuses.');
 if(f.status&&(appReport?!['PENDING','SUBMITTED','UNDER_REVIEW','CORRECTION_REQUIRED','APPROVED','REJECTED','WITHDRAWN'].includes(f.status):!['ACTIVE','INACTIVE','SUSPENDED','EXPIRED','REPLACED','REVOKED'].includes(f.status)))throw new FormError('Choose a status appropriate to the report.');return {filters:f,selected};}
export async function snapshot(db,user,places){if(!places.length)return {places,fs:[],apps:[]};const ids=places.map(p=>p.code),marks=ids.map(()=>'?').join(',');
 const fs=(await db.all(registrySelect+` WHERE f.panchayat_code IN (${marks}) LIMIT 10001`,ids)).filter(f=>can(user,'facilitators.view',f));
 const appPlaces=places.filter(p=>can(user,'applications.view',p));const apps=appPlaces.length?await db.all(`SELECT id,number,panchayat_code,full_name,status,submitted_at FROM gmf_applications WHERE panchayat_code IN (${appPlaces.map(()=>'?').join(',')}) LIMIT 10001`,appPlaces.map(p=>p.code)):[];
 if(fs.length>10000||apps.length>10000)throw new FormError('More than 10,000 records. Narrow your location filters.');
 const appIds=[...new Set(fs.map(f=>f.application_id))];const data=new Map();for(let offset=0;offset<appIds.length;offset+=400){const batch=appIds.slice(offset,offset+400);for(const a of await db.all(`SELECT id,mobile,payload,submitted_at,status FROM gmf_applications WHERE id IN (${batch.map(()=>'?').join(',')})`,batch))data.set(a.id,a);}
 for(const f of fs){f.application=data.get(f.application_id);f.report_status=f.ended||f.application?.status!=='APPROVED'?'INACTIVE':effectiveStatus(f);if(['REVOKED','REPLACED'].includes(f.status))f.report_status=f.status;}
 return {places,fs,apps};}
export function summarize(data,user){const {places,fs,apps}=data;const active=fs.filter(f=>f.report_status==='ACTIVE'),covered=new Set(active.filter(f=>f.role==='PRIMARY').map(f=>f.panchayat_code)),end=new Date(today());end.setUTCDate(end.getUTCDate()+30);const appAllowed=places.some(p=>can(user,'applications.view',p));return {panchayats:places.length,districts:new Set(places.map(p=>p.district_code)).size,blocks:new Set(places.map(p=>p.block_code)).size,facilitators:fs.length,active:active.length,covered:covered.size,vacant:places.length-covered.size,coverage:places.length?Math.round(covered.size/places.length*1000)/10:0,pending:appAllowed?apps.filter(a=>pending.has(a.status)).length:'Restricted',applications:appAllowed?apps.length:'Restricted',expiring:active.filter(f=>f.valid_until<=end.toISOString().slice(0,10)).length,suspended:fs.filter(f=>f.report_status==='SUSPENDED').length,expired:fs.filter(f=>f.report_status==='EXPIRED').length};}
const dateMatches=(value,f)=>!!value&&(!f.start||value>=f.start)&&(!f.end||value<=f.end);
export async function reportData(db,user,input,exporting=false){const capability=exporting?'reports.export':'dashboard.view';if(!hasCapability(user,capability))throw new FormError('Access denied.',403);const options=await placesFor(db,user,capability),{filters:f,selected}=validateFilters(input,options);if(['applications','progress','skills','equipment'].includes(f.report)&&!hasCapability(user,'applications.view'))throw new FormError('Application access is required for this report.',403);const data=await snapshot(db,user,selected),byPlace=new Map(selected.map(p=>[p.code,p]));let headers=[],rows=[];
 if(['coverage','vacancies'].includes(f.report)){headers=['District','Block','Panchayat','SEC code','Active','Pending','Covered','Vacant'];for(const p of selected){const summary=summarize({places:[p],fs:data.fs.filter(x=>x.panchayat_code===p.code),apps:data.apps.filter(x=>x.panchayat_code===p.code)},user);if(f.report==='vacancies'&&!summary.vacant)continue;rows.push([p.district_name,p.block_name,p.name,p.code,summary.active,summary.pending,summary.covered,summary.vacant]);}}
 else if(['applications','progress'].includes(f.report)){headers=['Application number','Name','District','Block','Panchayat','Status','Registered'];for(const a of data.apps){if(f.status&&(f.status==='PENDING'?!pending.has(a.status):a.status!==f.status)||!dateMatches(dateOf(a.submitted_at),f))continue;const p=byPlace.get(a.panchayat_code);rows.push([a.number,a.full_name,p.district_name,p.block_name,p.name,a.status,dateOf(a.submitted_at)]);}if(f.report==='progress'){const groups=new Map();for(const row of rows){const key=row[6].slice(0,7)+'|'+row[5];groups.set(key,(groups.get(key)||0)+1);}headers=['Registration month','Current application status','Applications'];rows=[...groups].sort().map(([key,n])=>[...key.split('|'),n]);}}
 else if(f.report==='history'){headers=['Facilitator ID','Name','Action','Recorded status','From panchayat','To panchayat','Role','Changed on'];if(data.fs.length){const ids=data.fs.map(x=>x.id),events=[];for(let offset=0;offset<ids.length;offset+=400){const batch=ids.slice(offset,offset+400);events.push(...await db.all(`SELECT facilitator_id,action,snapshot,created_at FROM gmf_registry_history WHERE facilitator_id IN (${batch.map(()=>'?').join(',')}) ORDER BY created_at DESC LIMIT 10001`,batch));if(events.length>10000)throw new FormError('Too much history. Narrow location filters.');}const byId=new Map(data.fs.map(x=>[x.id,x]));for(const e of events){const h=JSON.parse(e.snapshot),record=byId.get(e.facilitator_id);if(!byPlace.has(h.old.panchayat_code)||!byPlace.has(h.new.panchayat_code)||f.status&&h.new.status!==f.status||f.role&&h.new.role!==f.role)continue;const date=f.date_field==='expiry'?h.new.valid_until:f.date_field==='approval'?dateOf(record.approved_at):dateOf(record.application.submitted_at);if(!dateMatches(date,f))continue;rows.push([record.number,record.full_name,e.action,h.new.status,byPlace.get(h.old.panchayat_code).name,byPlace.get(h.new.panchayat_code).name,h.new.role,dateOf(e.created_at)]);}}}
 else{headers=['Facilitator ID','Name','District','Block','Panchayat','Role','Status','Registered','Approved','Valid until','Mobile'];const until=new Date(today());until.setUTCDate(until.getUTCDate()+30);for(const record of data.fs){if(f.status&&record.report_status!==f.status||f.role&&record.role!==f.role)continue;if(f.report==='expiring'&&(record.report_status!=='ACTIVE'||record.valid_until>until.toISOString().slice(0,10)))continue;const dates={registration:dateOf(record.application.submitted_at),approval:dateOf(record.approved_at),expiry:record.valid_until};if(!dateMatches(dates[f.date_field],f))continue;const p=byPlace.get(record.panchayat_code),base=[record.number,record.full_name,p.district_name,p.block_name,p.name,record.role,record.report_status];if(['skills','equipment'].includes(f.report)){if(!can(user,'applications.view',p))continue;const payload=JSON.parse(record.application.payload),values=payload[f.report==='skills'?3:4]?.[f.report];rows.push([...base,Array.isArray(values)&&values.length?values.join(', '):'Not provided']);}else rows.push([...base,dates.registration,dates.approval,dates.expiry,can(user,'contacts.view',p)?record.application.mobile:'Restricted']);}if(['skills','equipment'].includes(f.report))headers=headers.slice(0,7).concat(f.report==='skills'?'Skills':'Equipment');}
 return {headers,rows,filters:f,options,title:reportKinds[f.report],summary:summarize(data,user)};
}
