# Generated by Django 5.2.17 on 2026-09-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilitators', '0005_appointment_approval_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_digest', models.CharField(max_length=64)),
                ('replacement_digest', models.CharField(max_length=64)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=2000)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_history', to='facilitators.facilitator')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('view',),
            },
        ),
    ]
