# Generated by Django 5.2.17 on 2026-09-28 16:25

import apps.registrations.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('instructions', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('completed_step', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.registrations.models.draft_expiry)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('CORRECTION_REQUIRED', 'Correction required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=24)),
                ('full_name', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=10)),
                ('whatsapp', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.TextField(max_length=1500)),
                ('pin_code', models.CharField(max_length=6)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('current_organization', models.CharField(blank=True, max_length=180)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('media_experience', models.TextField(blank=True, max_length=2000)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ('other_skill', models.CharField(blank=True, max_length=200)),
                ('other_equipment', models.CharField(blank=True, max_length=200)),
                ('other_language', models.CharField(blank=True, max_length=100)),
                ('social_profiles', models.JSONField(blank=True, default=dict)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_relationship', models.CharField(blank=True, max_length=80)),
                ('emergency_mobile', models.CharField(blank=True, max_length=10)),
                ('consent_version', models.CharField(max_length=30)),
                ('consent_text', models.JSONField(default=dict)),
                ('consented_at', models.DateTimeField()),
                ('public_mobile_consent', models.BooleanField(default=False)),
                ('public_email_consent', models.BooleanField(default=False)),
                ('public_social_consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='locations.gramapanchayat')),
                ('equipment', models.ManyToManyField(blank=True, to='registrations.equipment')),
                ('languages', models.ManyToManyField(blank=True, to='registrations.language')),
                ('draft', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='registrations.registrationdraft')),
                ('skills', models.ManyToManyField(blank=True, to='registrations.skill')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reasons', models.JSONField(default=list)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_warnings', to='registrations.application')),
                ('other_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registrations.application')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'other_application'), name='unique_application_duplicate_warning')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=60)),
                ('file', models.FileField(max_length=250, upload_to='registrations/%Y/%m')),
                ('content_type', models.CharField(max_length=40)),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='registrations.application')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='registrations.registrationdraft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'slot'), name='unique_registration_draft_upload'), models.UniqueConstraint(fields=('application', 'slot'), name='unique_registration_application_upload'), models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('draft__isnull', False)), models.Q(('application__isnull', False), ('draft__isnull', True)), _connector='OR'), name='registration_upload_one_owner')],
            },
        ),
    ]
