# Generated by Django 5.2.17 on 2026-09-28 16:32

import unicodedata
from django.db import migrations, models


def backfill(apps, schema_editor):
    model = apps.get_model("registrations", "Application")
    for item in model.objects.using(schema_editor.connection.alias).all().iterator():
        item.normalized_name = " ".join(unicodedata.normalize("NFKC", item.full_name).casefold().split())[:180]
        item.save(using=schema_editor.connection.alias, update_fields=["normalized_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_seed_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=180),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
