# Generated by Django 5.2.17 on 2026-09-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_application_decided_at_application_decided_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='draft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='registrations.registrationdraft'),
        ),
    ]
