# Generated by Django 5.2.17 on 2026-09-28 15:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('district_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('block_code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
                ('lsg_code', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='locations.district')),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GramaPanchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('sec_local_body_code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
                ('lsg_code', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Use uppercase letters, numbers, underscores or hyphens.')])),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('office_phone', models.CharField(blank=True, max_length=30)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panchayats', to='locations.block')),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=500)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('summary', models.JSONField(default=dict)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.state'),
        ),
    ]
