const {chromium}=require("playwright");const fs=require("node:fs");const assert=require("node:assert/strict");
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.UI_BROWSER_CHANNEL||"chrome"});try{
const base=process.env.UI_BASE_URL||"http://127.0.0.1:8001";const f=JSON.parse(fs.readFileSync("artifacts/registry-fixtures.json","utf8"));const credentials=JSON.parse(fs.readFileSync("artifacts/ui-credentials.json","utf8"));
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.goto(base+"/accounts/login/");await page.getByLabel("Username").fill(credentials.username);await page.getByLabel(/^Password/).fill(credentials.password);await page.getByRole("button",{name:"Sign in securely"}).click();await page.waitForURL(base+"/");
async function generate(){await page.goto(base+"/cards/"+f.id+"/generate/");await page.locator("#id_reason").fill("Synthetic QA card issuance after verification.");await page.getByRole("button",{name:"Generate new card version",exact:true}).click();await page.waitForURL(new RegExp("/cards/"+f.id+"/[a-f0-9-]+/$"));return page.url();}
const first=await generate();assert.match(await page.locator(".page-heading").innerText(),/CURRENT/);assert.equal(await page.locator(".card-previews img").count(),2);await page.screenshot({path:"artifacts/cards-desktop.png",fullPage:true});
for(const [format,filename] of [["pdf","artifacts/card-size.pdf"],["print_pdf","artifacts/card-a4.pdf"]]){await page.goto(first+"actions/download/");await page.locator("#id_reason").fill("Synthetic QA test print.");await page.locator("#id_format").selectOption(format);const promise=page.waitForEvent("download");await page.getByRole("button",{name:"Download / reprint card",exact:true}).click();await (await promise).saveAs(filename);}
for(const width of [390,360,768]){await page.setViewportSize({width,height:900});await page.goto(first);const dims=await page.evaluate(()=>[innerWidth,document.documentElement.scrollWidth]);assert.ok(dims[1]<=dims[0]);await page.screenshot({path:"artifacts/cards-"+width+".png",fullPage:true});}
const second=await generate();await page.goto(first);assert.match(await page.locator(".page-heading").innerText(),/SUPERSEDED/);assert.equal(await page.locator(".card-previews img").count(),0);
await page.goto(second+"actions/revoke/");await page.locator("#id_reason").fill("Synthetic QA lost card.");await page.getByRole("button",{name:"Revoke card",exact:true}).click();await page.waitForURL(second);assert.match(await page.locator(".page-heading").innerText(),/REVOKED/);assert.deepEqual(errors,[]);
console.log("Card browser checks passed: front/back preview, both PDF downloads, responsive layouts, generation/version history, superseded/revoked preview denial and revocation.");
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
