const {chromium}=require("playwright");const fs=require("node:fs");const assert=require("node:assert/strict");
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.UI_BROWSER_CHANNEL||"chrome"});try{
const base=process.env.UI_BASE_URL||"http://127.0.0.1:8001";
const fixture=JSON.parse(fs.readFileSync("artifacts/verification-fixtures.json","utf8"));const credentials=JSON.parse(fs.readFileSync("artifacts/ui-credentials.json","utf8"));
const admin=await browser.newPage({viewport:{width:1440,height:1000}});const publicPage=await browser.newPage({viewport:{width:390,height:844}});const errors=[];for(const p of [admin,publicPage])p.on("pageerror",e=>errors.push(e.message));
async function privacy(){const html=await publicPage.content();for(const key of ["id","mobile","email","address","emergency"])assert.ok(!html.includes(fixture[key]),"Private field leaked: "+key);}
async function layout(name){const dims=await publicPage.evaluate(()=>[innerWidth,document.documentElement.scrollWidth]);assert.ok(dims[1]<=dims[0],name+" overflow");}
await publicPage.goto(base+"/verify/"+fixture.token+"/");await publicPage.getByRole("heading",{name:"Verified Media Facilitator",exact:true}).waitFor();await privacy();assert.equal(await publicPage.locator(".verify-portrait").evaluate(img=>img.complete&&img.naturalWidth>0),true);
for(const width of [390,360,768,1440]){await publicPage.setViewportSize({width,height:1000});await layout("public verification "+width);await publicPage.screenshot({path:"artifacts/verification-active-"+width+".png",fullPage:true});}
const json=await publicPage.request.get(base+"/api/v1/verify/"+fixture.token+"/");assert.equal(json.status(),200);const data=await json.json();assert.equal(data.is_authorized,true);for(const key of ["mobile","email","address","emergency_name","verification_token","id"])assert.ok(!(key in data));assert.match(json.headers()["cache-control"],/no-store/);
await admin.goto(base+"/accounts/login/");await admin.getByLabel("Username").fill(credentials.username);await admin.getByLabel(/^Password/).fill(credentials.password);await admin.getByRole("button",{name:"Sign in securely"}).click();await admin.waitForURL(base+"/");
await admin.goto(base+"/verification/"+fixture.id+"/");await admin.getByRole("heading",{name:"Verification link & QR",exact:true}).waitFor();assert.equal(await admin.locator("#verification-url").inputValue(),base+"/verify/"+fixture.token+"/");await admin.screenshot({path:"artifacts/verification-staff.png",fullPage:true});
const qr=await admin.request.get(base+"/verification/"+fixture.id+"/qr.png?download=1");assert.equal(qr.status(),200);assert.match(qr.headers()["content-disposition"],/attachment/);fs.writeFileSync("artifacts/verification-qr.png",await qr.body());
await admin.goto(base+"/facilitators/"+fixture.id+"/actions/suspend/");await admin.locator("#id_reason").fill("Synthetic verification browser test suspension.");await admin.getByRole("button",{name:"Confirm suspend",exact:true}).click();await admin.waitForURL(base+"/facilitators/"+fixture.id+"/");
await publicPage.setViewportSize({width:390,height:844});await publicPage.reload();await publicPage.getByRole("heading",{name:"Facilitator Suspended",exact:true}).waitFor();await privacy();await layout("suspended mobile");await publicPage.screenshot({path:"artifacts/verification-suspended-mobile.png",fullPage:true});
await admin.goto(base+"/verification/"+fixture.id+"/rotate/");await admin.locator("#id_reason").fill("Synthetic lost-link browser test.");await admin.locator("#id_confirmed").check();await admin.getByRole("button",{name:"Replace token",exact:true}).click();await admin.waitForURL(base+"/verification/"+fixture.id+"/");const replacement=await admin.locator("#verification-url").inputValue();assert.notEqual(replacement,base+"/verify/"+fixture.token+"/");
const old=await publicPage.goto(base+"/verify/"+fixture.token+"/");assert.equal(old.status(),404);await publicPage.getByRole("heading",{name:"Verification unavailable",exact:true}).waitFor();await publicPage.screenshot({path:"artifacts/verification-invalid-mobile.png",fullPage:true});
await publicPage.goto(replacement);await publicPage.getByRole("heading",{name:"Facilitator Suspended",exact:true}).waitFor();await privacy();assert.deepEqual(errors,[]);
console.log("Verification browser checks passed: anonymous mobile/desktop identity, no private-field leakage, portrait, public JSON, QR download, live suspension, token rotation and old-link denial; no JS errors.");
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
