# Generated by Django 5.2.17 on 2026-09-29 13:21

import apps.idcards.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilitators', '0005_appointment_approval_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=80, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('public_token', models.CharField(default=apps.idcards.models.card_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded')], default='ISSUED', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, max_length=2000)),
                ('source_digest', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('pdf', models.FileField(upload_to=apps.idcards.models.artifact_path)),
                ('print_pdf', models.FileField(upload_to=apps.idcards.models.artifact_path)),
                ('front', models.FileField(upload_to=apps.idcards.models.artifact_path)),
                ('back', models.FileField(upload_to=apps.idcards.models.artifact_path)),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('print_sha256', models.CharField(max_length=64)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilitators.facilitatorappointment')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='facilitators.facilitator')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_cards', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'default_permissions': ('view',),
                'constraints': [models.UniqueConstraint(fields=('facilitator', 'version'), name='unique_facilitator_card_version')],
            },
        ),
    ]
